---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testapi2
  region: us-east-1
  version: "1.20"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      # use existing EC2 key created from CLI
      publicKeyName: k8skeypair2


# DISABLED FOR NOW
# fargateProfiles:
#   - name: fp-default
#     selectors:
#       # All workloads in the "default" Kubernetes namespace will be
#       # scheduled onto Fargate:
#       - namespace: default
#       # All workloads in the "kube-system" Kubernetes namespace will be
#       # scheduled onto Fargate:
#       - namespace: kube-system