apiVersion: v1
kind: Service
metadata:
  name: rust-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: rust-testapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
